REBOOT_ON_CRASH = True
KILL_GECKODRIVER_ON_EXIT = True
KILL_FIREFOX_ON_EXIT = True

# Logging
LOG_TIMESTAMPS = True
LOG_TO_FILE = True
DISABLE_UNIMPORTANT_MODULE_LOGGING = True

# Discord
DISCORD_BOT_ENABLED = True
RELEASE_BOT = True
SUBMIT_ADDITIONAL_DATA = True
ALLOW_RECOVERY_SHEET_ADJUSTMENT = True
ALLOW_DEATH_SHEET_ADJUSTMENT = True
DISCORD_SERVER = "COVID19-EU"
DISCORD_DEV_SERVER = "Private Testing"
NOVEL_BOT_ID = 685802076831219746

DISCORD_STAFF_ROLES = {"staff", "the real slip shady"}
DISCORD_DEFAULT_ROLES = {"interpol"}

# Browser
SELENIUM_BROWSER_ALWAYS_ON = True
SELENIUM_FIREFOX_HEADLESS = False

# API Downloader
COVIDTRACKING_CACHE_TIMEOUT = 30
DRIVE_CACHE_TIMEOUT = 360

# Scraper
ALLOW_SCREENSHOTS = True
# Surrounding words used in the learning model. WARNING - Changing this will break previous learned models!
SURROUNDING_WORD_COUNT = 5
OVERWRITE_SURROUNDING_NUMBERS = True
DISABLE_SHEET_ERROR_CHECKING = False