# Logging
LOG_TIMESTAMPS = False
LOG_TO_FILE = True
DISABLE_UNIMPORTANT_MODULE_LOGGING = True

# Discord
DISCORD_BOT_ENABLED = True
RELEASE_BOT = True
SUBMIT_ADDITIONAL_DATA = True
ALLOW_RECOVERY_SHEET_ADJUSTMENT = True
ALLOW_DEATH_SHEET_ADJUSTMENT = True

# Browser
SELENIUM_BROWSER_ALWAYS_ON = True
SELENIUM_FIREFOX_HEADLESS = True

# API Downloader
COVIDTRACKING_CACHE_TIMEOUT = 30
DRIVE_CACHE_TIMEOUT = 360

# Scraper
ALLOW_SCREENSHOTS = True
# Surrounding words used in the learning model. WARNING - Changing this will break previous learned models!
SURROUNDING_WORD_COUNT = 5
DISABLE_SHEET_ERROR_CHECKING = False